version: "3"
services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on: 
      - backend
    ports:
      - "3000:3000"