version: "3"
services: 
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=5000
      - RUN_ENV=docker
    ports:
      - "5000:5000"
    restart: always
  client:
    build:
      context: ./server/client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server/client:/app
    environment: 
      - RUN_ENV=docker
    depends_on: 
      - server
    ports:
      - "3000:3000"