export const FETCH_USER = "FETCH_USER";
export const CREATE_MATERIAL = "CREATE_MATERIAL";
export const FETCH_MATERIALS = "FETCH_MATERIALS";
export const DELETE_MATERIAL = "DELETE_MATERIAL";
export const EDIT_MATERIAL = "EDIT_MATERIAL ";
export const FETCH_MATERIAL = "FETCH_MATERIAL";
export const FETCH_ALL_MATERIALS = "FETCH_ALL_MATERIALS";
export const FETCH_VIDEOS = "FETCH_VIDEOS";
