export const CHECK_USER_AUTHENTICATION = "CHECK_USER_AUTHENTICATION";
export const FETCH_USER = "FETCH_USER";
export const LOGIN_USER = "LOGIN_USER";

export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const FETCH_SUBJECT = "GET_SUBJECT";
export const FETCH_SUBJECTS = "FETCH_SUBJECTS";
export const EDIT_SUBJECT = "EDIT_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";

export const CREATE_TOPIC = "CREATE_TOPIC";
export const FETCH_TOPICS = "FETCH_TOPICS";
export const DELETE_TOPIC = "DELETE_TOPIC";
export const EDIT_TOPIC = "EDIT_TOPIC ";
export const FETCH_TOPIC = "FETCH_TOPIC";
export const FETCH_ALL_TOPICS = "FETCH_ALL_TOPICS";

export const FETCH_NOTES = "FETCH_NOTES";
export const CREATE_NOTES = "CREATE_NOTES";
export const EDIT_NOTES = "EDIT_NOTES";
export const DELETE_NOTES = "DELETE_NOTES";

export const FETCH_REVISION_QUESTIONS = "FETCH_REVISION_QUESTIONS";
export const CREATE_REVISION_QUESTIONS = "CREATE_REVISION_QUESTIONS";
export const EDIT_REVISION_QUESTIONS = "EDIT_REVISION_QUESTIONS";
export const DELETE_REVISION_QUESTIONS = "DELETE_REVISION_QUESTIONS";

export const FETCH_MARKING_SCHEME = "FETCH_MARKING_SCHEME";
export const CREATE_MARKING_SCHEME = "CREATE_MARKING_SCHEME";
export const EDIT_MARKING_SCHEME = "EDIT_MARKING_SCHEME";
export const DELETE_MARKING_SCHEME = "DELETE_MARKING_SCHEME";

export const FETCH_VIDEO = "FETCH_VIDEO";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const EDIT_VIDEO = "EDIT_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";

export const UPLOAD_FILE = "UPLOAD_FILE";
